[package]
name = "trinket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3
lto = "thin"

[dependencies]
cozy-chess = "0.2.1"