[package]
name = "trinket"
version = "3.0.0"
repository = "https://github.com/DkeRee/Trinket"
edition = "2021"

[dependencies]
cozy-chess = "0.3.1"

[profile.dev]
opt-level = 3
lto = "thin"

[profile.release]
codegen-units = 1
lto = "fat"